package com.example.SmartGov.enums;

public enum ComplaintCategory {
    WATER_SUPPLY,
    ELECTRICITY_BILL,
    WATER_BILL,
    ROAD_MAINTENANCE,
    GARBAGE_COLLECTION,
    STREET_LIGHT,
    DRAINAGE_SYSTEM,
    PROPERTY_TAX,
    BIRTH_CERTIFICATE,
    DEATH_CERTIFICATE,
    OTHER
}
