spring.application.name=SmartGov

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smartGov
spring.datasource.username=postgres
spring.datasource.password=Ariba@25

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


#cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000,http://localhost:5500,http://127.0.0.1:5500,file://
#cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#cors.allowed-headers=*
#cors.allow-credentials=true

jwt.secret=SGVsbG9Xb3JsZEhlbGxvV29ybGRIZWxsb1dvcmxkSGVsbG9Xb3JsZA==
jwt.expiration=86400000

# OTP Configuration
otp.expiry.minutes=10
otp.max.attempts=3
otp.max.resend=3

# Email for development
spring.mail.host=localhost
spring.mail.port=2525
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.username=ashishranjan5241@gmail.com